# Generated by Django 5.0.2 on 2024-02-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(3, 'User'), (2, 'doc'), (1, 'admin')], default=1, max_length=50),
        ),
    ]
