# Generated by Django 5.0.2 on 2024-02-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0007_alter_appointment_date_of_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
