# Generated by Django 5.0.2 on 2024-02-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0008_alter_appointment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='prescription',
            field=models.ImageField(null=True, upload_to='prescription/patient_pres'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='remark',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
