# Generated by Django 5.0.2 on 2024-02-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0010_alter_appointment_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='recommendedtest',
            field=models.TextField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='prescription',
            field=models.TextField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'doc'), (3, 'User')], default=1, max_length=50),
        ),
    ]
