# Generated by Django 5.0.2 on 2024-02-25 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0015_doctorreg_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorreg',
            name='profile_pic',
        ),
    ]
